name: Branch Checks

on:
  push:
    branches-ignore:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        # tmpfs makes DB faster by using RAM
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      GEMFILE_RUBY_VERSION: 3.2
      RAILS_DB_HOST: localhost
      RAILS_DB_USER: postgres
      RAILS_DB_PASSWORD: postgres
      ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: testing
      ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: testing
      ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: testing

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: Create DB
        run: |
          bin/rails db:setup

      - name: Compile assets
        run: |
          bundle exec rake assets:precompile

      - name: Run tests
        run: |
          bundle exec rspec
